/* Museum Mouse atlas. Data stays local; no sign-up or analytics. */
'use strict';
const GOLD_PIN_VARIANTS=256;
const $=s=>document.querySelector(s), fmt=n=>n.toLocaleString(), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const worldZoom=()=>document.documentElement.clientWidth<=760?0.8:1.55;
let rows=[],filtered=[],meta={},map,loaded=false,selected=null,savedOnly=false,page=25,mode='satellite',detailToken=0;
const shardCache=new Map();let stars=new Set();
try{const raw=JSON.parse(localStorage.getItem('museum-mouse-stars-v1')||'[]');if(Array.isArray(raw))stars=new Set(raw.filter(x=>typeof x==='string'));}catch{}
function message(s){$('#map-message').textContent=s;$('#map-message').hidden=!s;}
function storeStars(){try{localStorage.setItem('museum-mouse-stars-v1',JSON.stringify([...stars]));}catch{message('Browser storage is unavailable. Your pilot stars will last for this session only.');}}
function star(id){stars.has(id)?stars.delete(id):stars.add(id);storeStars();$('#saved-count').textContent=stars.size; if(savedOnly)applyFilters(false);else renderList(); if(selected?.[0]===id){const b=$('#detail-star');if(b){b.textContent=stars.has(id)?'★ Saved as a pilot':'☆ Add to pilot shortlist';b.setAttribute('aria-pressed',stars.has(id));}}updateStarLayer();}
function feature(r){return{type:'Feature',geometry:{type:'Point',coordinates:[r[2],r[3]]},properties:{id:r[0],name:r[1],country:r[4],type:r[6],pin:goldPinName(r[0])}};}
function geo(list){return{type:'FeatureCollection',features:list.map(feature)};}
function style(){return{version:8,glyphs:'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Imagery © Esri, Maxar, Earthstar Geographics, and the GIS User Community'},street:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}},layers:[{id:'background',type:'background',paint:{'background-color':'#081321'}},{id:'satellite',type:'raster',source:'satellite',paint:{'raster-saturation':-.35,'raster-brightness-max':.7}},{id:'street',type:'raster',source:'street',layout:{visibility:'none'}}]};}
function updateStarLayer(){if(loaded)map.getSource('pilots')?.setData(geo(filtered.filter(r=>stars.has(r[0]))));}
function setMode(next){mode=next;['satellite','street'].forEach(k=>{$('#'+k).classList.toggle('active',k===next);$('#'+k).setAttribute('aria-pressed',k===next);if(loaded)map.setLayoutProperty(k,'visibility',k===next?'visible':'none');});}
function fly(rowsToFit){if(!loaded||!rowsToFit.length)return;if(rowsToFit.length===1){map.flyTo({center:[rowsToFit[0][2],rowsToFit[0][3]],zoom:13,duration:900});return;}const b=new maplibregl.LngLatBounds();rowsToFit.forEach(r=>b.extend([r[2],r[3]]));map.fitBounds(b,{padding:65,maxZoom:10,duration:900});}
function renderList(){const list=filtered.slice(0,page);$('#results').innerHTML=list.length?list.map(r=>`<div class="museum-row ${selected?.[0]===r[0]?'selected':''}"><button class="row-main" data-select="${esc(r[0])}"><strong>${esc(r[1])}</strong><small>${esc(r[5]==='Unknown'?r[4]:r[5]+', '+r[4])}</small></button><button class="star ${stars.has(r[0])?'saved':''}" data-star="${esc(r[0])}" aria-label="${stars.has(r[0])?'Unstar':'Star'} ${esc(r[1])}" aria-pressed="${stars.has(r[0])}">${stars.has(r[0])?'★':'☆'}</button></div>`).join(''):`<p class="empty">${savedOnly?'No starred museums match. Explore the map and use ☆ to make your shortlist.':'No museums match these filters. Try a broader search or reset.'}</p>`;$('#more').hidden=filtered.length<=page;$('#result-status').textContent=`${fmt(filtered.length)} ${savedOnly?'pilot candidates':'results'}`;}
function applyFilters(zoom=true){const q=norm($('#search').value.trim()),country=$('#country').value,type=$('#type').value,budget=$('#budget').value;page=25;filtered=rows.filter(r=>(!q||r.search.includes(q))&&(!country||r[4]===country)&&(!type||r[6]===type)&&(!budget||r[7]===budget)&&(!savedOnly||stars.has(r[0])));renderList();if(loaded){map.getSource('museums').setData(geo(filtered));updateStarLayer();if(zoom&&(q||country||savedOnly)&&filtered.length)fly(filtered);}}
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
async function selectMuseum(id){const r=rows.find(r=>r[0]===id);if(!r)return;selected=r;if(innerWidth<=760)document.querySelector('.map-panel').scrollIntoView({block:'start',behavior:'smooth'});const token=++detailToken;$('#detail').hidden=false;$('#detail-content').innerHTML=`<span class="tag">${esc(r[6])}</span><h2>${esc(r[1])}</h2><p>Loading museum details…</p>`;renderList();if(loaded){map.flyTo({center:[r[2],r[3]],zoom:Math.max(map.getZoom(),11),duration:850});map.getSource('selected').setData(geo([r]));}
try{if(!shardCache.has(r[9])){shardCache.set(r[9],await readMuseumJSON(`data/details-${r[9]}.json`));}if(token!==detailToken)return;const d=shardCache.get(r[9])[id];if(!d)throw new Error('Museum details unavailable');const site=safeLink(d.website),gq=encodeURIComponent(r[1]+' '+r[5]+' '+r[4]);const key=window.MUSEUM_ATLAS_CONFIG?.googleMapsEmbedKey;
$('#detail-content').innerHTML=`<span class="tag">${esc(r[6])}</span><h2>${esc(r[1])}</h2><p>${esc(r[5])} · ${esc(r[4])}</p><button class="primary" id="detail-star" aria-pressed="${stars.has(id)}">${stars.has(id)?'★ Saved as a pilot':'☆ Add to pilot shortlist'}</button><dl><dt>Scale</dt><dd>${esc(d.budget_band)}</dd>${d.budget_value?`<dt>Basis</dt><dd>${esc(d.budget_currency)} ${fmt(d.budget_value)} · ${esc(d.budget_year)}<br>${esc(d.budget_basis)}${safeLink(d.budget_source)?`<br><a target="_blank" rel="noopener" href="${esc(safeLink(d.budget_source))}">Financial source ↗</a>`:''}</dd>`:''}<dt>Commission</dt><dd>${esc(d.commissioning_band)}</dd><dt>Film status</dt><dd>${esc(d.film_status)}</dd><dt>Coordinates</dt><dd>${r[3].toFixed(5)}, ${r[2].toFixed(5)}</dd><dt>Data snapshot</dt><dd>${esc(meta.updated.slice(0,10))}</dd><dt>Operating now?</dt><dd>Check with the institution</dd><dt>Approver / AI policy</dt><dd>Not yet confirmed</dd><dt>Place type</dt><dd>${esc(d.settlement_type)}</dd><dt>Contact</dt><dd>${d.email?esc(d.email):'Email not listed'}${d.phone?'<br>'+esc(d.phone):''}</dd></dl><div class="detail-links">${site?`<a target="_blank" rel="noopener noreferrer" href="${esc(site)}">Museum website ↗</a>`:'<span class="muted">Website not listed</span>'}<a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/@?api=1&map_action=map&center=${r[3]},${r[2]}&zoom=18&basemap=satellite">Google Maps · satellite ↗</a><a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${r[3]},${r[2]}">Google Street View ↗</a><a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/search/?api=1&query=${gq}">Find institution on Google Maps ↗</a></div>${key?`<iframe title="Google map of ${esc(r[1])}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed/v1/view?key=${encodeURIComponent(key)}&center=${r[3]},${r[2]}&zoom=16&maptype=satellite" allowfullscreen></iframe>`:''}<p class="source-links">${(d.sources||[]).map((s,i)=>safeLink(s)?`<a href="${esc(s)}" target="_blank" rel="noopener">Source ${i+1} ↗</a>`:'').join(' · ')}<br>Public records, not a verified operating listing. Street View may not be available at this location.</p>`;$('#detail-star').onclick=()=>star(id);
}catch(e){if(token===detailToken)$('#detail-content').innerHTML=`<h2>${esc(r[1])}</h2><p>Details could not load. Please select the museum again to retry.</p>`;}}
function openData(){$('#data-dialog').showModal();}
async function init(){try{const data=await readMuseumJSON('data/museums.json');rows=data.rows;meta=data.meta;rows.forEach(r=>{r.search=norm(r[1]+' '+r[4]+' '+r[5]);});$('#mapped').textContent=fmt(meta.records);$('#countries').textContent=fmt(meta.countries);$('#all-count').textContent=fmt(meta.records);$('#saved-count').textContent=stars.size;for(const [idx,el] of [[4,'#country'],[6,'#type']]){[...new Set(rows.map(r=>r[idx]))].sort().forEach(v=>$(el).add(new Option(v,v)));}$('#coverage-stats').innerHTML=`<strong>${fmt(meta.records)} records</strong> · ${fmt(meta.websites)} with websites · ${fmt(meta.emails)} with email · ${fmt(meta.phones)} with phone<br>${fmt(meta.budgets)} with sourced operating scale<br>Snapshot: ${esc(meta.updated.slice(0,10))}<br>${(meta.warnings||[]).map(esc).join('<br>')}`;applyFilters(false);
if(window.MUSEUM_ATLAS_CONFIG?.googleMapsJavaScriptKey){try{map=await window.createGoogleAtlasMap({key:window.MUSEUM_ATLAS_CONFIG.googleMapsJavaScriptKey,data:geo(filtered),onSelect:selectMuseum,isStarred:id=>stars.has(id)});loaded=true;setMode(mode);message("");return;}catch(e){message("Google Maps could not load. Using the open map instead.");}}
try{map=new maplibregl.Map({container:'map',style:style(),center:[8,22],zoom:worldZoom(),attributionControl:true,maxZoom:19,renderWorldCopies:false});map.scrollZoom.disable();map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('load',()=>{map.setProjection({type:'globe'});for(let i=0;i<GOLD_PIN_VARIANTS;i++)map.addImage('museum-gold-pin-'+i,makePin(i),{pixelRatio:2});map.addSource('museums',{type:'geojson',data:geo(filtered),cluster:true,clusterMaxZoom:13,clusterRadius:38});map.addSource('pilots',{type:'geojson',data:geo(filtered.filter(r=>stars.has(r[0])))});map.addSource('selected',{type:'geojson',data:geo([])});map.addLayer({id:'clusters',type:'symbol',source:'museums',filter:['has','point_count'],layout:{'icon-image':['concat','museum-gold-pin-',['to-string',['%',['get','cluster_id'],GOLD_PIN_VARIANTS]]],'icon-anchor':'bottom','icon-size':1.05,'icon-allow-overlap':true,'text-field':['get','point_count_abbreviated'],'text-font':['Open Sans Semibold'],'text-size':11,'text-offset':[0,-3.65],'text-allow-overlap':true},paint:{'text-color':'#35260e','text-halo-color':'#fff0bd','text-halo-width':.65}});map.addLayer({id:'points',type:'symbol',source:'museums',filter:['!',['has','point_count']],layout:{'icon-image':['get','pin'],'icon-anchor':'bottom','icon-size':['interpolate',['linear'],['zoom'],1,.65,10,1],'icon-allow-overlap':true}});map.addLayer({id:'pilot-points',type:'symbol',source:'pilots',layout:{'icon-image':['get','pin'],'icon-anchor':'bottom','icon-size':1.15,'icon-allow-overlap':true}});map.addLayer({id:'selected-point',type:'symbol',source:'selected',layout:{'icon-image':['get','pin'],'icon-anchor':'bottom','icon-size':1.3,'icon-allow-overlap':true}});map.addLayer({id:'museum-names',type:'symbol',source:'museums',minzoom:10,filter:['!',['has','point_count']],layout:{'text-field':['get','name'],'text-font':['Open Sans Semibold'],'text-size':12,'text-anchor':'top','text-offset':[0,.5],'text-max-width':16},paint:{'text-color':'#fff','text-halo-color':'#07101b','text-halo-width':2}});loaded=true;setMode(mode);message('');map.on('click','clusters',async e=>{const f=e.features[0];try{const z=await map.getSource('museums').getClusterExpansionZoom(f.properties.cluster_id);map.easeTo({center:f.geometry.coordinates,zoom:z});}catch{}});['points','pilot-points','selected-point'].forEach(l=>map.on('click',l,e=>selectMuseum(e.features[0].properties.id)));['clusters','points','pilot-points'].forEach(l=>{map.on('mouseenter',l,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',l,()=>map.getCanvas().style.cursor='');});});map.on('error',e=>{if(!loaded)message('Map imagery is taking longer to load. Search results remain available.');});}catch{message('The map needs WebGL. The searchable museum list and pilot shortlist are still available.');}
}catch(e){message('Museum records could not load. Refresh the page to retry.');$('#result-status').textContent='Data unavailable';}}
let debounce;$('#search').addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(()=>applyFilters(),280);});['country','type','budget'].forEach(id=>$('#'+id).onchange=()=>applyFilters());$('#results').onclick=e=>{const st=e.target.closest('[data-star]'),sl=e.target.closest('[data-select]');if(st)star(st.dataset.star);else if(sl)selectMuseum(sl.dataset.select);};$('#more').onclick=()=>{page+=25;renderList();};function tab(saved){savedOnly=saved;$('#all-tab').classList.toggle('active',!saved);$('#saved-tab').classList.toggle('active',saved);$('#all-tab').setAttribute('aria-pressed',!saved);$('#saved-tab').setAttribute('aria-pressed',saved);applyFilters();}$('#all-tab').onclick=()=>tab(false);$('#saved-tab').onclick=()=>tab(true);$('#reset').onclick=()=>{['search','country','type','budget'].forEach(id=>$('#'+id).value='');tab(false);if(loaded)map.flyTo({center:[8,22],zoom:worldZoom()});};$('#world').onclick=()=>{if(loaded)map.flyTo({center:[8,22],zoom:worldZoom()});};$('#satellite').onclick=()=>setMode('satellite');$('#street').onclick=()=>setMode('street');$('#about').onclick=openData;$('#coverage-button').onclick=openData;$('.dialog-close').onclick=()=>$('#data-dialog').close();$('#close-detail').onclick=()=>{$('#detail').hidden=true;selected=null;detailToken++;renderList();if(loaded)map.getSource('selected').setData(geo([]));};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#data-dialog').open)$('#close-detail').click();});
init();

// A bounded set of gilded finishes keeps the world map light on GPU memory.
function pinHash(value){let hash=2166136261;for(const ch of String(value)){hash^=ch.charCodeAt(0);hash=Math.imul(hash,16777619);}return hash>>>0;}
function goldPinName(id){return 'museum-gold-pin-'+(pinHash(id)%GOLD_PIN_VARIANTS);}
function makePin(variant=0){
 const c=document.createElement('canvas');c.width=72;c.height=108;
 const x=c.getContext('2d');
 let seed=pinHash('museum-gold-leaf-'+variant);
 const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const hue=42+random()*8, warmth=random()*6-3;
 const gold=(s,l,a=1)=>`hsla(${hue},${s}%,${l+warmth}%,${a})`;
 // The shaft stays polished steel; only the spherical head is gilded.
 x.beginPath();x.ellipse(36,103,13,4,0,0,Math.PI*2);x.fillStyle='rgba(0,0,0,.24)';x.fill();
 const shaft=x.createLinearGradient(31,0,40,0);
 shaft.addColorStop(0,'#797d86');shaft.addColorStop(.5,'#fff');shaft.addColorStop(1,'#a0a9b4');
 x.fillStyle=shaft;x.beginPath();x.moveTo(32,42);x.lineTo(40,42);x.lineTo(36,104);x.closePath();x.fill();
 const highlightX=25+random()*6,highlightY=15+random()*5;
 const ball=x.createRadialGradient(highlightX,highlightY,1,38,32,31);
 ball.addColorStop(0,gold(92,89));ball.addColorStop(.22,gold(88,72));
 ball.addColorStop(.48,gold(83,56));ball.addColorStop(.72,gold(78,48));ball.addColorStop(1,gold(76,27));
 x.save();x.beginPath();x.arc(36,29,25,0,Math.PI*2);x.clip();
 x.fillStyle=ball;x.fillRect(10,3,52,52);
 // Irregular thin leaf patches, with quiet seams and creases rather than glitter.
 for(let i=0;i<58;i++){
  const px=10+random()*52,py=3+random()*52,size=2+random()*9,angle=random()*Math.PI*2;
  x.beginPath();
  for(let corner=0;corner<5;corner++){
   const a=angle+corner*Math.PI*2/5,r=size*(.55+random()*.5);
   const xx=px+Math.cos(a)*r,yy=py+Math.sin(a)*r;
   if(corner===0)x.moveTo(xx,yy);else x.lineTo(xx,yy);
  }
  x.closePath();x.fillStyle=gold(80+random()*16,random()>.43?76:32,.08+random()*.18);x.fill();
  x.strokeStyle=gold(88,88,.1+random()*.15);x.lineWidth=.35+random()*.5;x.stroke();
 }
 for(let i=0;i<135;i++){
  x.fillStyle=gold(88,random()>.5?92:25,.045+random()*.11);
  x.fillRect(11+random()*50,4+random()*50,.3+random()*.9,.25+random()*.6);
 }
 // Preserve roundness over the leaf texture and add a soft studio reflection.
 const shadow=x.createRadialGradient(27,18,8,39,33,32);
 shadow.addColorStop(0,'rgba(82,46,0,0)');shadow.addColorStop(.65,'rgba(82,46,0,.02)');shadow.addColorStop(1,'rgba(54,27,0,.42)');
 x.fillStyle=shadow;x.fillRect(10,3,52,52);
 const sheen=x.createRadialGradient(highlightX,highlightY,0,highlightX,highlightY,12);
 sheen.addColorStop(0,'rgba(255,252,218,.55)');sheen.addColorStop(1,'rgba(255,252,218,0)');
 x.fillStyle=sheen;x.fillRect(10,3,52,52);x.restore();
 x.beginPath();x.arc(36,29,25,0,Math.PI*2);x.strokeStyle=gold(90,84,.8);x.lineWidth=1.2;x.stroke();
 return x.getImageData(0,0,72,108);
}
document.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>{$('#country').value=b.dataset.country;applyFilters();document.getElementById('atlas').scrollIntoView({behavior:'smooth'});});
