'use strict';
// Optional Google Maps provider. Only loaded when the owner configures a restricted browser key.
// Render visible Supercluster results, not a DOM marker for every museum in the database.
window.createGoogleAtlasMap=async function({key,data,onSelect,isStarred}){
  await new Promise((resolve,reject)=>{window.museumGoogleReady=resolve;window.gm_authFailure=()=>reject(new Error('Google Maps authorization failed'));const script=document.createElement('script');script.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&v=quarterly&loading=async&callback=museumGoogleReady';script.onerror=()=>reject(new Error('Google Maps unavailable'));document.head.append(script);});
  const native=new google.maps.Map(document.getElementById('map'),{center:{lat:22,lng:8},zoom:2,mapTypeId:'satellite',mapTypeControl:false,streetViewControl:true,fullscreenControl:false,zoomControl:true,gestureHandling:'greedy'});
  let points=data.features,index=new Supercluster({radius:45,maxZoom:17}).load(points),markers=[],selectedData=null;
  const redraw=()=>{const bounds=native.getBounds();if(!bounds)return;markers.forEach(m=>m.setMap(null));markers=[];const sw=bounds.getSouthWest(),ne=bounds.getNorthEast();const zoom=Math.floor(native.getZoom()||2);const groups=index.getClusters([sw.lng(),sw.lat(),ne.lng(),ne.lat()],zoom);for(const f of groups){const p=f.properties,cluster=!!p.cluster,starred=!cluster&&isStarred(p.id);const marker=new google.maps.Marker({map:native,position:{lng:f.geometry.coordinates[0],lat:f.geometry.coordinates[1]},title:cluster?`${p.point_count} museums`:'Museum details',label:cluster?{text:String(p.point_count_abbreviated),color:'#142020',fontSize:'12px'}:undefined,icon:{path:google.maps.SymbolPath.CIRCLE,scale:cluster?(p.point_count>1000?25:18):(starred?8:6),fillColor:starred?'#f28b54':'#e7ef70',fillOpacity:.95,strokeColor:'#fffbc6',strokeWeight:1}});marker.addListener('click',()=>{if(cluster){native.panTo(marker.getPosition());native.setZoom(index.getClusterExpansionZoom(p.cluster_id));}else onSelect(p.id);});markers.push(marker);}};
  native.addListener('idle',redraw);
  const source=name=>({setData:collection=>{if(name==='museums'){points=collection.features;index=new Supercluster({radius:45,maxZoom:17}).load(points);redraw();}else if(name==='pilots')redraw();else selectedData=collection;}});
  return{getSource:source,getZoom:()=>native.getZoom()||2,flyTo:({center,zoom})=>{native.panTo({lng:center[0],lat:center[1]});if(zoom!==undefined)native.setZoom(Math.round(zoom));},fitBounds:(b,opts)=>{const sw=b.getSouthWest(),ne=b.getNorthEast();native.fitBounds({west:sw.lng,south:sw.lat,east:ne.lng,north:ne.lat},opts?.padding||60);},setLayoutProperty:(layer,prop,val)=>{if(val==='visible')native.setMapTypeId(layer==='satellite'?'satellite':'roadmap');}};
};
